name: coptic_app
description: A new Flutter project for learning Coptic.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/instapay_qr.jpeg
    - assets/data/
    - assets/images/words/
    - assets/images/words/p12/
    - assets/images/words/p34/
    - assets/images/words/p56/
    - assets/images/words/prep/
    - assets/images/words/uni/
    - assets/images/words/sn/
    - assets/audio/letters/
    - assets/audio/words/
    - assets/audio/words/grad/
    - assets/audio/words/p12/
    - assets/audio/words/p34/
    - assets/audio/words/p56/
    - assets/audio/words/prep/
    - assets/audio/words/qana/
    - assets/audio/words/sec/
    - assets/audio/words/serv/
    - assets/audio/words/st/
    - assets/audio/words/uni/
    - assets/audio/hymns/
    - assets/audio/hymns/grad/
    - assets/audio/hymns/grad/lvl1/
    - assets/audio/hymns/grad/lvl2/
    - assets/audio/hymns/grad/theme/
    - assets/audio/hymns/kg/
    - assets/audio/hymns/p12/
    - assets/audio/hymns/p34/
    - assets/audio/hymns/p34/lvl1/
    - assets/audio/hymns/p34/lvl2/
    - assets/audio/hymns/p34/theme/
    - assets/audio/hymns/p56/
    - assets/audio/hymns/p56/lvl1/
    - assets/audio/hymns/p56/lvl2/
    - assets/audio/hymns/p56/theme/
    - assets/audio/hymns/prep/
    - assets/audio/hymns/prep/lvl1/
    - assets/audio/hymns/prep/lvl2/
    - assets/audio/hymns/prep/theme/
    - assets/audio/hymns/primary_1/
    - assets/audio/hymns/primary_3/
    - assets/audio/hymns/primary_5/
    - assets/audio/hymns/qana/
    - assets/audio/hymns/qana/lvl1/
    - assets/audio/hymns/qana/theme/
    - assets/audio/hymns/sec/
    - assets/audio/hymns/sec/lvl1/
    - assets/audio/hymns/sec/lvl2/
    - assets/audio/hymns/sec/theme/
    - assets/audio/hymns/serv/
    - assets/audio/hymns/serv/lvl1/
    - assets/audio/hymns/serv/lvl2/
    - assets/audio/hymns/serv/theme/
    - assets/audio/hymns/st/
    - assets/audio/hymns/st/lvl1/
    - assets/audio/hymns/st/lvl2/
    - assets/audio/hymns/st/theme/
    - assets/audio/hymns/uni/
    - assets/audio/hymns/uni/lvl1/
    - assets/audio/hymns/uni/lvl2/
    - assets/audio/hymns/uni/theme/

  fonts:
    - family: AbraamLegacy
      fonts:
        - asset: assets/fonts/ABRAAM_0.ttf
    - family: Antinoou
      fonts:
        - asset: assets/fonts/Antinoou.ttf
    - family: CopticStandard
      fonts:
        - asset: assets/fonts/CopticStandard.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

